stages:
  - test_unitaire
  - test_integration
  - analyse_sonar
  - verification_quality_gate

variables:
  SONAR_TOKEN: "989c7a1c5ab516c4f1f075255da3fa8d26d14c05"

before_script:
  - apt-get update -qy
  - apt-get install -y openjdk-11-jre
  - apt-get install -y php-cli php-xml
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install

test_unitaire:
  stage: test_unitaire
  script:
    - vendor/bin/phpunit --coverage-html coverage/unit_coverage.xml tests/unitTests
  artifacts:
    paths:
      - coverage/unit_coverage.xml

test_integration:
  stage: test_integration
  script:
    - vendor/bin/phpunit --coverage-html coverage/coverage.xml tests/integrationTests
  artifacts:
    paths:
      - coverage/coverage.xml

analyse_sonar:
  stage: analyse_sonar
  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  only:
    - master

verification_quality_gate:
  stage: verification_quality_gate
  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.qualitygate.wait=true
  only:
    - master
